# Generated by Django 5.0.2 on 2024-02-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
